packages:
  - 'packages/*'
  - '.'
allowBuilds:
  '@firebase/util': true
  '@parcel/watcher': true
  core-js: true
  esbuild: true
  protobufjs: true
  vue-demi: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
